### ISSUE TITLE
Default export doesn't seem to be work

### ISSUE THREAD

**Issue by Siilwyn** [drwpow/gqlmin#254]
As per the readme `import gqlmin from 'gqlmin';` does not give a function.
Instead `gqlmin.default` is where the main function resides. Atleast in the context of an `mjs` file with Node.js 20.

:bulb: I prefer named exports, maybe it's an idea to export the function so `import { gqlmin } from 'gqlmin';` works (too)?

**Comment by drwpow** [comment]
Thanks for the suggestion! This is likely just from (very) old packaging. The problem you described is from CommonJS <> ESM interop that’s gotten a lot better since this package was written.

I don’t have a ton of time this week, but perhaps soon I can update this package & push a more modern version where the internals don’t change, but the bundling is updated to current standards (kinda forgot about this package, honestly!)

**Comment by Siilwyn** [comment]
Figured something like that would be it! :)
Purely an ESM build would be grant, could be a nice moment to bring this to `1.0.0`.


As a sidenote the CLI doesn't work without installing `fs-extra` which resides in the devDependencies, but I'd rather use this package without the CLI dependency bloat. Splitting the CLI into another package is however more work to maintain and such so understand the choice to keep it together.

**Comment by drwpow** [comment]
Yeah this package is basically in maintenance mode, and won’t receive any major updates, but we can at least just fix everything & modernize it. And remove unnecessary deps that are from many Node versions ago.

**Comment by drwpow** [comment]
Actually did have some time today, and published `0.2.0` that only ships ESM, and removes everything but `chalk` from the CLI. Library itself is unchanged. Thanks for the issue! Please let me know if the new version has something unexpected

**Comment by Siilwyn** [comment]
Thank you, that was quick!

**Comment by Siilwyn** [comment]
Oh @drwpow `dist` is missing from the published package files, but `main` is pointing to it.

To clarify my request for a version 1, I don't expect any major changes but atleast then the package follows semver rules. Under version 1 every change is (potentially) breaking.

**Comment by drwpow** [comment]
Oh, sorry—dunno what happened there. Fixed!

**Comment by drwpow** [comment]
> Under version 1 every change is (potentially) breaking.

This isn’t “official” but I personally like the pattern of: pre-1.0, minor is breaking; patch isn’t (what esbuild and three.js does, though the latter is decidedly never shipping a 1.0 and treating minor as major).
